"""
PDF export utility using ReportLab (pure Python, no system deps).
Falls back to plain HTML download if ReportLab is unavailable.
"""

from __future__ import annotations

import io
import logging
import re
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


def _markdown_to_plain(md: str) -> str:
    """Strip most Markdown to plain text for PDF rendering."""
    text = re.sub(r"#{1,6}\s+", "", md)        # headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.+?)\*",     r"\1", text)    # italic
    text = re.sub(r"`(.+?)`",       r"\1", text)    # inline code
    text = re.sub(r"```[\s\S]+?```", "[code block]", text)  # code block
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)  # links
    text = re.sub(r"^\s*[-*+]\s+", "  • ", text, flags=re.MULTILINE)
    return text.strip()


def generate_design_pdf(
    topic: str,
    content: str,
    author_name: Optional[str] = None,
) -> bytes:
    """
    Generate a PDF for a system design.

    Args:
        topic: Design topic title
        content: Markdown content
        author_name: Optional author name

    Returns:
        PDF as bytes
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            HRFlowable,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "Title",
            parent=styles["Title"],
            fontSize=24,
            textColor=colors.HexColor("#6C63FF"),
            spaceAfter=6,
        )
        subtitle_style = ParagraphStyle(
            "Subtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.grey,
            spaceAfter=20,
        )
        heading_style = ParagraphStyle(
            "Heading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#1a1a2e"),
            spaceBefore=16,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=10,
            leading=16,
            spaceAfter=6,
        )

        elements = []

        # Header
        elements.append(Paragraph(f"System Design: {topic}", title_style))
        subtitle = f"Generated by DesignMentor AI  •  {datetime.now().strftime('%B %d, %Y')}"
        if author_name:
            subtitle += f"  •  {author_name}"
        elements.append(Paragraph(subtitle, subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#6C63FF")))
        elements.append(Spacer(1, 20))

        # Content — parse markdown into sections
        current_section_lines: list[str] = []
        for line in content.split("\n"):
            stripped = line.strip()

            # Section heading
            if stripped.startswith("## "):
                # Flush previous
                if current_section_lines:
                    para_text = _markdown_to_plain("\n".join(current_section_lines))
                    if para_text:
                        elements.append(Paragraph(para_text.replace("\n", "<br/>"), body_style))
                    current_section_lines = []
                elements.append(Paragraph(stripped[3:], heading_style))

            elif stripped.startswith("### "):
                if current_section_lines:
                    para_text = _markdown_to_plain("\n".join(current_section_lines))
                    if para_text:
                        elements.append(Paragraph(para_text.replace("\n", "<br/>"), body_style))
                    current_section_lines = []
                sub_style = ParagraphStyle(
                    "Sub", parent=styles["Heading3"],
                    fontSize=12, textColor=colors.HexColor("#333"),
                    spaceBefore=10, spaceAfter=4,
                )
                elements.append(Paragraph(stripped[4:], sub_style))

            else:
                current_section_lines.append(line)

        # Flush remaining
        if current_section_lines:
            para_text = _markdown_to_plain("\n".join(current_section_lines))
            if para_text:
                elements.append(Paragraph(para_text.replace("\n", "<br/>"), body_style))

        # Footer spacer
        elements.append(Spacer(1, 30))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
        elements.append(Paragraph(
            "Powered by DesignMentor AI — designmentor.ai",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                           textColor=colors.grey, alignment=1)
        ))

        doc.build(elements)
        return buffer.getvalue()

    except ImportError:
        logger.warning("reportlab not installed — returning HTML bytes instead")
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>System Design: {topic}</title>
<style>
  body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
  h1 {{ color: #6C63FF; }} h2 {{ color: #1a1a2e; border-bottom: 1px solid #eee; }}
  pre {{ background: #f4f4f4; padding: 12px; border-radius: 4px; overflow-x: auto; }}
  code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }}
</style></head><body>
<h1>System Design: {topic}</h1>
<p style="color:grey">Generated by DesignMentor AI — {datetime.now().strftime('%B %d, %Y')}</p>
<hr>
<div id="content">{content}</div>
</body></html>"""
        return html.encode("utf-8")


def generate_interview_pdf(
    topic: str,
    turns: list[dict],
    scores: dict,
    author_name: Optional[str] = None,
) -> bytes:
    """
    Generate a PDF report for a completed interview.

    Args:
        topic: Interview topic
        turns: List of {turn_number, question, answer, evaluation}
        scores: {overall, correctness, scalability, tradeoffs, communication, depth}
        author_name: Optional candidate name
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                rightMargin=2*cm, leftMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()

        title_style  = ParagraphStyle("T", parent=styles["Title"], fontSize=22,
                                      textColor=colors.HexColor("#6C63FF"))
        heading_style = ParagraphStyle("H", parent=styles["Heading2"], fontSize=13,
                                       textColor=colors.HexColor("#1a1a2e"), spaceBefore=14)
        body_style   = ParagraphStyle("B", parent=styles["Normal"], fontSize=10, leading=16)
        label_style  = ParagraphStyle("L", parent=styles["Normal"], fontSize=9,
                                      textColor=colors.grey)

        elements = []
        elements.append(Paragraph(f"Interview Report: {topic}", title_style))
        info = f"DesignMentor AI  •  {datetime.now().strftime('%B %d, %Y')}"
        if author_name:
            info = f"{author_name}  •  {info}"
        elements.append(Paragraph(info, label_style))
        elements.append(Spacer(1, 12))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=colors.HexColor("#6C63FF")))
        elements.append(Spacer(1, 16))

        # Score table
        score_data = [
            ["Dimension", "Score / 10"],
            ["Overall",        f"{scores.get('overall', 0):.1f}"],
            ["Correctness",    f"{scores.get('correctness', 0):.1f}"],
            ["Scalability",    f"{scores.get('scalability', 0):.1f}"],
            ["Trade-offs",     f"{scores.get('tradeoffs', 0):.1f}"],
            ["Communication",  f"{scores.get('communication', 0):.1f}"],
            ["Depth",          f"{scores.get('depth', 0):.1f}"],
        ]
        table = Table(score_data, colWidths=[10*cm, 4*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#6C63FF")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",    (0, 0), (-1, 0), 11),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#f9f9ff")]),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ALIGN",       (1, 0), (1, -1), "CENTER"),
            ("TOPPADDING",  (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(Paragraph("Performance Scores", heading_style))
        elements.append(table)
        elements.append(Spacer(1, 20))

        # Turns
        for turn in turns:
            elements.append(Paragraph(
                f"Question {turn.get('turn_number', '')}", heading_style))
            elements.append(Paragraph(
                f"<b>Q:</b> {turn.get('question', '')}", body_style))
            elements.append(Spacer(1, 6))
            elements.append(Paragraph("<b>Your Answer:</b>", body_style))
            answer_text = _markdown_to_plain(turn.get("answer", ""))
            elements.append(Paragraph(answer_text.replace("\n", "<br/>"), body_style))
            elements.append(Spacer(1, 6))
            elements.append(Paragraph("<b>Evaluation:</b>", body_style))
            eval_text = _markdown_to_plain(turn.get("evaluation", ""))
            elements.append(Paragraph(eval_text.replace("\n", "<br/>"), body_style))
            elements.append(HRFlowable(width="100%", thickness=0.5,
                                       color=colors.lightgrey))
            elements.append(Spacer(1, 12))

        doc.build(elements)
        return buffer.getvalue()

    except ImportError:
        logger.warning("reportlab not installed — returning HTML bytes")
        content = f"<h1>Interview: {topic}</h1>"
        for t in turns:
            content += f"<h3>Q{t.get('turn_number')}: {t.get('question')}</h3>"
            content += f"<p><b>Answer:</b> {t.get('answer')}</p>"
            content += f"<p><b>Evaluation:</b> {t.get('evaluation')}</p><hr>"
        html = f"<html><body>{content}</body></html>"
        return html.encode("utf-8")
