"""
Multi-agent orchestrator for high-quality system design generation.

Pipeline:
  1. RequirementsAgent  — clarify functional + non-functional requirements
  2. CapacityAgent      — estimate storage, bandwidth, QPS
  3. DesignAgent        — build the core architecture
  4. CriticAgent        — review and improve the design
  5. Merge              — combine into final polished output
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from app.chains import _invoke_with_retry, _load_prompt

logger = logging.getLogger(__name__)


async def run_multi_agent_design(topic: str) -> str:
    """
    Run all design agents in sequence and merge the output.

    Args:
        topic: System to design (e.g. "Instagram", "Uber")

    Returns:
        Polished final design as markdown string
    """
    logger.info("Multi-agent design started for: %s", topic)

    system_msg = SystemMessage(content=_load_prompt("system.txt"))

    # --- Agent 1: Requirements ---
    req_prompt = f"""You are a Requirements Analyst.
For the system: **{topic}**

Identify:
1. Functional Requirements (core features, user stories)
2. Non-Functional Requirements (scale, latency, availability, consistency)
3. Key constraints and assumptions

Be precise. Output in clean markdown."""

    requirements = await _invoke_with_retry(
        [system_msg, HumanMessage(content=req_prompt)],
        {"temperature": 0.3}
    )
    logger.info("RequirementsAgent completed.")

    # --- Agent 2: Capacity Estimation ---
    cap_prompt = f"""You are a Capacity Estimation Expert.
For the system: **{topic}**

Given these requirements:
{requirements[:800]}

Calculate:
1. Daily Active Users (DAU) and Monthly Active Users (MAU)
2. Requests Per Second (read/write QPS)
3. Storage requirements (daily + 5-year)
4. Bandwidth requirements
5. Number of servers needed

Show your math. Be specific with numbers."""

    capacity = await _invoke_with_retry(
        [system_msg, HumanMessage(content=cap_prompt)],
        {"temperature": 0.2}
    )
    logger.info("CapacityAgent completed.")

    # --- Agent 3: Core Design ---
    design_prompt = f"""You are a Senior Staff Engineer designing **{topic}**.

Requirements Summary:
{requirements[:600]}

Capacity Estimates:
{capacity[:400]}

Design the complete system:
1. High-Level Architecture (major components)
2. API Design (key endpoints with request/response)
3. Database Design (schema, SQL vs NoSQL choice, sharding)
4. Caching Strategy (Redis, CDN, what to cache)
5. Message Queues & Async Processing
6. Scaling & Load Balancing
7. Fault Tolerance & Recovery

Use markdown with clear sections and tables."""

    core_design = await _invoke_with_retry(
        [system_msg, HumanMessage(content=design_prompt)],
        {"temperature": 0.5}
    )
    logger.info("DesignAgent completed.")

    # --- Agent 4: Critic Review ---
    critic_prompt = f"""You are a Principal Engineer reviewing a system design for **{topic}**.

Review this design and identify:
1. **Bottlenecks** — performance or scalability issues
2. **Missing Components** — what's not addressed
3. **Trade-off Analysis** — key decisions and their consequences
4. **Security Concerns** — authentication, authorization, data protection
5. **Cost Optimizations** — where to reduce infrastructure costs

Be constructive but rigorous. Output improvements as a section to append."""

    critique = await _invoke_with_retry(
        [system_msg, HumanMessage(content=f"{critic_prompt}\n\nDesign:\n{core_design[:1200]}")],
        {"temperature": 0.4}
    )
    logger.info("CriticAgent completed.")

    # --- Merge all sections ---
    final = f"""# System Design: {topic}

---

## 📋 Requirements

{requirements}

---

## 📊 Capacity Estimation

{capacity}

---

## 🏗️ System Architecture

{core_design}

---

## 🔍 Critical Review & Trade-offs

{critique}

---

*Generated by DesignMentor AI Multi-Agent System*
"""
    logger.info("Multi-agent design complete for: %s", topic)
    return final
